version: '3'
services:
  chatgpt-telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/home/appuser/app
      - .env:/home/appuser/app/.env
    restart: always
